options:
  logging: CLOUD_LOGGING_ONLY
  substitution_option: 'ALLOW_LOOSE'

timeout: '700s'

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/chuzz-app/discord-bot', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/chuzz-app/discord-bot']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
      'run',
      'services',
      'replace',
      './service.yaml',
      '--region',
      'europe-west1'
    ]

tags:
  - main
  - dev

images:
  - 'gcr.io/chuzz-app/discord-bot'