apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: discord-bot
spec:
  template:
    spec:
      containers:
      - image: gcr.io/chuzz-app/discord-bot
        env:
        - name: DISCORD_TOKEN
          value: MTAyNjMwMzc2MDAyMjEzMDY5OA.G8B74-.KXh3GMOSrgKLZMaWW54tWjtjrQYLunzeZ2C1R8
        - name: DISCORD_CHANNEL_ID
          value: '1030960875907076156'